{% set data = load_setup_py_data() %}

package:
    name: pyqtads
    version: {{ data.get('version') }}

source:
    path: ../

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt --conda-recipe

requirements:
    build:
        - python
        - setuptools
        - pyqt>=5.9
        - sip>=4.19
    run:
        - python
        - pyqt>=5.9
        - sip>=4.19
        - pywin32  [win]

test:
    imports:
        - PyQtAds

about:
    home: {{ data.get('url') }}
    license: {{ data.get('license') }}
    license_family: LGPL
    license_file: 'LICENSE.md'
    summary: {{ data.get('description') }}
    description: {{ data.get('description') }}
    doc_url: ''
    dev_url: {{ data.get('url') }}

extra:
    recipe-maintainers: 'nicolas.elie@cnrs.fr'
